export type FinancialNoteCategory = 'Accounting Policy' | 'General Disclosure' | 'Balance Sheet Note' | 'Income Statement Note' | 'Cash Flow Note'
export interface FinancialNoteTemplate { id:string; noteNumber:string; title:string; category:FinancialNoteCategory; statementType:string; sortOrder:number; isSystemDefault:boolean; isActive:boolean }
export const FINANCIAL_NOTE_TEMPLATES_KEY='fitpro_financial_note_templates_v1'
const entries: [string,string,FinancialNoteCategory,string][] = [
 ['1','Accounting Policies','Accounting Policy','Notes'],['2','Significant Judgements and Estimates','General Disclosure','Notes'],['3','Financial Risk Management','General Disclosure','Notes'],
 ['11','Cash and Cash Equivalents','Balance Sheet Note','Balance Sheet'],['12','Accounts Receivable','Balance Sheet Note','Balance Sheet'],['13','Prepayments and Advances','Balance Sheet Note','Balance Sheet'],['14','Short-Term Investments','Balance Sheet Note','Balance Sheet'],['15','Loans Receivable','Balance Sheet Note','Balance Sheet'],['16','Inventories','Balance Sheet Note','Balance Sheet'],['17','Other Current Assets','Balance Sheet Note','Balance Sheet'],['18','Leasehold Properties','Balance Sheet Note','Balance Sheet'],['19','Property, Plant and Equipment','Balance Sheet Note','Balance Sheet'],['20','Bank Overdraft','Balance Sheet Note','Balance Sheet'],['21','Accounts Payable / Creditors','Balance Sheet Note','Balance Sheet'],['22','Accrued Expenses','Balance Sheet Note','Balance Sheet'],['23','Deferred Income','Balance Sheet Note','Balance Sheet'],['24','Taxes Payable','Balance Sheet Note','Balance Sheet'],['25','Borrowings','Balance Sheet Note','Balance Sheet'],['26','Reserves','Balance Sheet Note','Balance Sheet'],['27','Prior Year Adjustments','Balance Sheet Note','Balance Sheet'],['28','Retained Earnings / Accumulated Fund','Balance Sheet Note','Balance Sheet'],
 ['31','Revenue','Income Statement Note','Income Statement'],['32','Grants and Donations','Income Statement Note','Income Statement'],['33','Other Income','Income Statement Note','Income Statement'],['34','Welfare Expenses','Income Statement Note','Income Statement'],['35','General Expenses','Income Statement Note','Income Statement'],['36','Repairs and Maintenance','Income Statement Note','Income Statement'],['37','Utilities','Income Statement Note','Income Statement'],['38','Depreciation Expense','Income Statement Note','Income Statement'],['39','Finance Costs','Income Statement Note','Income Statement'],['40','Tax Expense','Income Statement Note','Income Statement'],
 ['41','Cash Flow Reconciliation','Cash Flow Note','Cash Flow'],['42','Non-Cash Transactions','Cash Flow Note','Cash Flow'],['43','Related Party Transactions','General Disclosure','Notes'],['44','Contingent Liabilities','General Disclosure','Notes'],['45','Commitments and Subsequent Events','General Disclosure','Notes'],
]
export const DEFAULT_FINANCIAL_NOTE_TEMPLATES: FinancialNoteTemplate[] = entries.map(([noteNumber,title,category,statementType],i)=>({id:`fnt_${noteNumber}`,noteNumber,title,category:category as FinancialNoteCategory,statementType,sortOrder:i+1,isSystemDefault:true,isActive:true}))
export function loadFinancialNoteTemplates(){try{const v=JSON.parse(localStorage.getItem(FINANCIAL_NOTE_TEMPLATES_KEY)||'null');const rows=Array.isArray(v)?v:DEFAULT_FINANCIAL_NOTE_TEMPLATES;return rows.map((r:FinancialNoteTemplate)=>r)}catch{return DEFAULT_FINANCIAL_NOTE_TEMPLATES}}
export function saveFinancialNoteTemplates(v:FinancialNoteTemplate[]){localStorage.setItem(FINANCIAL_NOTE_TEMPLATES_KEY,JSON.stringify(v))}
