import { useState } from 'react'
import { PageHeader, Button, Badge, Field, Input, Select } from '../../../components/ui'
import { useToast } from '../../../context/ToastContext'
import { loadFinancialNoteTemplates, saveFinancialNoteTemplates, type FinancialNoteTemplate } from '../../../lib/financialNoteTemplates'
export function FinancialNoteTemplatesPage(){
 const toast=useToast(); const [rows,setRows]=useState<FinancialNoteTemplate[]>(loadFinancialNoteTemplates()); const [q,setQ]=useState('')
 const persist=(next:FinancialNoteTemplate[])=>{setRows(next);saveFinancialNoteTemplates(next)}
 const filtered=rows.filter(r=>`${r.noteNumber} ${r.title} ${r.category}`.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.sortOrder-b.sortOrder)
 const add=()=>{const title=prompt('Note title');if(!title)return;const no=prompt('Note number','46')||'';persist([...rows,{id:`fnt_${Date.now()}`,noteNumber:no,title,category:'General Disclosure',statementType:'Notes',sortOrder:rows.length+1,isSystemDefault:false,isActive:true}]);toast.success('Note template added')}
 return <div><PageHeader title="Financial Statement Note Templates" desc="System-defined note catalogue. Existing Notes to Accounts remain linked to the Chart of Accounts; this catalogue controls the professional note framework." actions={<Button onClick={add}>Add note template</Button>}/><div className="card p-4"><div className="mb-4 max-w-md"><Field label="Search"><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Number, title or category"/></Field></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="bg-[#2e75b6] text-left text-white"><th className="p-3">No.</th><th className="p-3">Note title</th><th className="p-3">Category</th><th className="p-3">Statement</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-b border-line"><td className="p-3 font-bold">{r.noteNumber}</td><td className="p-3">{r.title}{r.isSystemDefault&&<span className="ml-2 text-[10px] text-mist">SYSTEM DEFAULT</span>}</td><td className="p-3">{r.category}</td><td className="p-3">{r.statementType}</td><td className="p-3"><Badge tone={r.isActive?'lime':'zinc'}>{r.isActive?'ACTIVE':'INACTIVE'}</Badge></td><td className="p-3"><div className="flex gap-2"><Button variant="ghost" onClick={()=>persist(rows.map(x=>x.id===r.id?{...x,isActive:!x.isActive}:x))}>{r.isActive?'Deactivate':'Activate'}</Button><Button variant="ghost" onClick={()=>{const title=prompt('Rename note',r.title);if(title)persist(rows.map(x=>x.id===r.id?{...x,title}:x))}}>Rename</Button></div></td></tr>)}</tbody></table></div></div></div>
}